language: node_js
node_js: stable

script:
  - npm run build

deploy:
  provider: surge
  project: ./public
  domain: recruiter-dashboard.surge.sh
  cleanup: false
  skip_cleanup: true
  on:
    branch: main